### ISSUE TITLE
Implicit dependency on httpclient

### ISSUE THREAD

**Issue by skwp** [zipmark/zipmark-ruby#14]
If you try to use this gem, out of the box, you get:

NameError: uninitialized constant Zipmark::Adapters::HTTPClientAdapter::HTTPClient

It seems you are using the httpclient gem under the hood. It should be added to the gemspec so that users get the dependency correctly.

**Comment by skwp** [comment]
Is this because you offer a choice between httpclient and httparty? At the very least this should be part of the README?

**Comment by jakehow** [comment]
@skwp yes there is a choice, as well as a simple adapter pattern to use any client library which can support the necessary features.  See the code in: https://github.com/zipmark/zipmark-ruby/tree/master/lib/zipmark/adapters

At the time of authorship httparty did not do digest auth correctly, but that may have changed.

**Comment by jakehow** [comment]
@skwp also there arent great docs around this feature, but the client takes an optional adapter, if you are using a custom adapater, see the inline documentation here:

https://github.com/zipmark/zipmark-ruby/blob/master/lib/zipmark/client.rb#L19-L33

**Comment by skwp** [comment]
Thanks for the info
